source 'https://rubygems.org'
ruby '2.0.0'


gem 'rails', '4.0.4'

group :development do
  gem 'sqlite3', '1.3.8'
end

gem 'protected_attributes'
gem 'bcrypt-ruby', '3.1.2'
gem 'sass-rails', '4.0.1'
gem 'uglifier', '2.1.1'
gem 'coffee-rails', '4.0.1'
gem "jquery-rails", "< 3.0.0"
gem 'turbolinks', '1.1.1'
gem 'jbuilder', '1.0.2'
gem 'therubyracer'
gem 'passenger'
gem 'bootstrap-sass', '2.3.2.0'
gem 'sprockets', '2.11.0'
gem 'will_paginate'



group :production do
  gem 'pg', '0.15.1'
  gem 'rails_12factor', '0.0.2'
end
